# SPDX-License-Identifier: (GPL-2.0+ OR BSD-3-Clause)

dtb-$(CONFIG_ARCH_GOOGLE) += \
	lga-blazer.dtb \
	lga-frankel.dtb \
	lga-mustang.dtb \
	mbu-cubs.dtb

# LOCAL: bootable image for the Pixel bootloader, see mbu-ufs-placeholder.dtso.
mbu-cubs-bootable-dtbs := mbu-cubs.dtb mbu-ufs-placeholder.dtbo
dtb-$(CONFIG_ARCH_GOOGLE) += mbu-cubs-bootable.dtb
