/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */
/*
 * Clocks of the Google Tensor G6 (malibu) SoC, managed by the CPM.
 *
 * A clock is identified by its subsystem clock manager (LPCM) and its id
 * within that LPCM. Both are part of the CPM firmware interface.
 *
 * Copyright 2025 Google LLC
 */

#ifndef _DT_BINDINGS_CLOCK_GOOGLE_MBU_CPM_H
#define _DT_BINDINGS_CLOCK_GOOGLE_MBU_CPM_H

/* LPCM ids */
#define MBU_LPCM_GSM               0
#define MBU_LPCM_AOSS_AONSS        1
#define MBU_LPCM_AOSS_AMBSS        2
#define MBU_LPCM_AOSS_PG           3
#define MBU_LPCM_AOSS_AON          4
#define MBU_LPCM_LSIO_E            5
#define MBU_LPCM_LSIO_S            6
#define MBU_LPCM_HSIO_N            7
#define MBU_LPCM_HSIO_S            8
#define MBU_LPCM_PCIE              9
#define MBU_LPCM_GPCA              10
#define MBU_LPCM_FABDISP           11
#define MBU_LPCM_FABHBW            12
#define MBU_LPCM_MEMSS             13
#define MBU_LPCM_FABMED            14
#define MBU_LPCM_FABSTBY           15
#define MBU_LPCM_FABSYSS           16
#define MBU_LPCM_CPU               17
#define MBU_LPCM_CPU_MAIN          18
#define MBU_LPCM_CPU_CCM1A         19
#define MBU_LPCM_CPU_CCM1B         20
#define MBU_LPCM_CCM2              21
#define MBU_LPCM_AURORA            22
#define MBU_LPCM_CODEC_3P          23
#define MBU_LPCM_G2D               24
#define MBU_LPCM_GCV               25
#define MBU_LPCM_ISPBE             26
#define MBU_LPCM_ISPFE             27
#define MBU_LPCM_GPU               28
#define MBU_LPCM_GPU_REMOTE_FLL    29
#define MBU_LPCM_GPU_REMOTE_SENSOR 30
#define MBU_LPCM_TPU               31
#define MBU_LPCM_TPU_REMOTE        32
#define MBU_LPCM_BMSM              33
#define MBU_LPCM_CPUACC            34
#define MBU_LPCM_DPU               35
#define MBU_LPCM_GDMC              36
#define MBU_LPCM_GMC0              37
#define MBU_LPCM_GMC1              38
#define MBU_LPCM_GMC2              39
#define MBU_LPCM_GMC3              40
#define MBU_LPCM_GPCM_AMB          41
#define MBU_LPCM_GPCM_INFRA        42
#define MBU_LPCM_GSA               43

/* Clock ids within their LPCM */
#define MBU_AOSS_PG_AMB_SPI3_APB_CLK               13
#define MBU_AOSS_PG_AMB_SPI3_PERI_CLK              31
#define MBU_DPU_DP0_PIX_CLK                        0
#define MBU_DPU_DSI0_PIX_CLK                       1
#define MBU_DPU_DSI1_PIX_CLK                       2
#define MBU_DPU_DSI_PHY_CLK                        3
#define MBU_DPU_BE_CLK                             4
#define MBU_DPU_FE0_CLK                            5
#define MBU_DPU_FE1_CLK                            6
#define MBU_GPCM_HSION_PLL_DP_CLK                  0
#define MBU_GPCM_DPU_CHNL_CLK                      0
#define MBU_GPCM_ISPBE_CHNL_CLK                    1
#define MBU_GPCM_GCV_CHNL_CLK                      2
#define MBU_GPCM_ISPFE_CHNL_CLK                    3
#define MBU_GPCM_ISPFE_SCAN_WORDCLKHS_CLK          4
#define MBU_GPCM_ISPFE_P2D6_400M_CLK               5
#define MBU_GPCM_ISPFE_P2D4_600M_CLK               6
#define MBU_HSION_USBC_STICKY_CLK                  0
#define MBU_HSION_USBC_NON_STICKY_CLK              1
#define MBU_HSION_USBDP_USBDRD_REF_CLK             2
#define MBU_HSION_USBCTRLREF_CLK                   3
#define MBU_HSION_USB2_PHY_RESET_CLK               4
#define MBU_HSION_USB3DP_PHY_RESET_CLK             5
#define MBU_HSION_USBDP_U3PHY_FW_CLK               6
#define MBU_HSION_USBDP_U2PHY_APB_CLK              7
#define MBU_HSION_USBDP_USBDRD_BUS_CLK             8
#define MBU_HSION_USBDP_TOP_CLK                    9
#define MBU_HSIO_N_USB2AUX_CTRL_VAUX_STICKY_CLK    10
#define MBU_HSIO_N_USB2AUX_CTRL_VCC_NON_STICKY_CLK 11
#define MBU_HSIO_N_USB2AUX_PHY_RESET_CLK           12
#define MBU_HSIO_N_USBDP_USB2AUX_CTRL_BUS_CLK      13
#define MBU_HSIO_N_USBDP_USB2AUX_PHY_APB_CLK       14
#define MBU_HSIO_N_USBDP_USB2AUX_CTRL_REF_CLK      15
#define MBU_HSIO_N_USBDP_USB2AUX_SUSPEND_CLK       16
#define MBU_HSIO_N_USBDP_SCLK0_CLK                 17
#define MBU_HSIO_N_SRESETN0_CLK                    18
#define MBU_HSIO_N_USBDP_AUX16M_CLK                19
#define MBU_HSIO_N_VIDEO_0_CLK                     20
#define MBU_HSIO_N_DP_PIXEL_0_CLK                  21
#define MBU_HSIO_N_USBDP_PIXEL_0_CLK               22
#define MBU_HSIO_N_SW_PIXEL0CLK_VIDEOBUFF_RSTN_CLK 23
#define MBU_HSIO_N_USBDP_DPTOP_CLK                 24
#define MBU_HSIO_N_CSR_CLK                         25
#define MBU_HSIO_N_SDP_0_CLK                       26
#define MBU_HSIO_N_TRNG_CLK                        27
#define MBU_HSIO_N_PRESETN0_CLK                    28
#define MBU_HSIO_N_HDCP22_CLK                      29
#define MBU_HSIO_N_DP_VCC_CLK                      30
#define MBU_HSIO_N_USBDP_ESM_CLK                   31
#define MBU_HSIO_N_MAXI_CLK                        32
#define MBU_HSIOS_GPIO_REF_CLK                     0
#define MBU_HSIOS_MPHY_REF_CLK                     1
#define MBU_HSIOS_UFS_CLK                          2
#define MBU_HSIOS_CP_CORE_CLK                      3
#define MBU_HSIOS_UFS_DEEP_H8_CLK                  4
#define MBU_LSIO_S_PWM_CLK                         0
#define MBU_LSIO_S_M0_CLK                          1
#define MBU_LSIO_S_M1_CLK                          2
#define MBU_LSIO_S_M2_CLK                          3
#define MBU_LSIO_S_M3_CLK                          4
#define MBU_LSIO_S_M4_CLK                          5
#define MBU_LSIO_S_M5_CLK                          6
#define MBU_LSIO_S_M6_CLK                          7
#define MBU_LSIO_S_M7_CLK                          8
#define MBU_LSIO_S_I2C_0_CLK                       9
#define MBU_LSIO_S_I3C_0_CLK                       10
#define MBU_LSIO_S_I2C_1_CLK                       11
#define MBU_LSIO_S_I3C_1_CLK                       12
#define MBU_LSIO_S_I2C_2_CLK                       13
#define MBU_LSIO_S_I3C_2_CLK                       14
#define MBU_LSIO_S_I2C_3_CLK                       15
#define MBU_LSIO_S_I3C_3_CLK                       16
#define MBU_LSIO_S_I2C_4_CLK                       17
#define MBU_LSIO_S_I3C_4_CLK                       18
#define MBU_LSIO_S_SPI_0_CLK                       19
#define MBU_LSIO_S_UART_0_CLK                      20
#define MBU_LSIO_S_SPI_1_CLK                       21
#define MBU_LSIO_S_UART_1_CLK                      22
#define MBU_LSIO_S_SPI_2_CLK                       23
#define MBU_LSIO_S_UART_2_CLK                      24
#define MBU_LSIO_S_SPI_3_CLK                       25
#define MBU_LSIO_S_UART_3_CLK                      26
#define MBU_LSIO_S_QSPI_CLK                        27
#define MBU_LSIO_S_I2C_0_CFG_CLK                   28
#define MBU_LSIO_S_I3C_0_CFG_CLK                   29
#define MBU_LSIO_S_I2C_1_CFG_CLK                   30
#define MBU_LSIO_S_I3C_1_CFG_CLK                   31
#define MBU_LSIO_S_I2C_2_CFG_CLK                   32
#define MBU_LSIO_S_I3C_2_CFG_CLK                   33
#define MBU_LSIO_S_I2C_3_CFG_CLK                   34
#define MBU_LSIO_S_I3C_3_CFG_CLK                   35
#define MBU_LSIO_S_I2C_4_CFG_CLK                   36
#define MBU_LSIO_S_I3C_4_CFG_CLK                   37
#define MBU_LSIO_S_SPI_0_CFG_CLK                   38
#define MBU_LSIO_S_UART_0_CFG_CLK                  39
#define MBU_LSIO_S_SPI_1_CFG_CLK                   40
#define MBU_LSIO_S_UART_1_CFG_CLK                  41
#define MBU_LSIO_S_SPI_2_CFG_CLK                   42
#define MBU_LSIO_S_UART_2_CFG_CLK                  43
#define MBU_LSIO_S_SPI_3_CFG_CLK                   44
#define MBU_LSIO_S_UART_3_CFG_CLK                  45
#define MBU_LSIO_S_QSPI_CFG_CLK                    46
#define MBU_LSIO_S_PWM_CFG_CLK                     47
#define MBU_LSIO_S_GPIO_CLK                        48
#define MBU_LSIO_E_I2C_0_CLK                       0
#define MBU_LSIO_E_I3C_0_CLK                       1
#define MBU_LSIO_E_I2C_1_CLK                       2
#define MBU_LSIO_E_I3C_1_CLK                       3
#define MBU_LSIO_E_I2C_2_CLK                       4
#define MBU_LSIO_E_I3C_2_CLK                       5
#define MBU_LSIO_E_I2C_3_CLK                       6
#define MBU_LSIO_E_I3C_3_CLK                       7
#define MBU_LSIO_E_I2C_4_CLK                       8
#define MBU_LSIO_E_I3C_4_CLK                       9
#define MBU_LSIO_E_SPI_0_CLK                       10
#define MBU_LSIO_E_UART_0_CLK                      11
#define MBU_LSIO_E_SPI_1_CLK                       12
#define MBU_LSIO_E_UART_1_CLK                      13
#define MBU_LSIO_E_I2C_0_CFG_CLK                   14
#define MBU_LSIO_E_I3C_0_CFG_CLK                   15
#define MBU_LSIO_E_I2C_1_CFG_CLK                   16
#define MBU_LSIO_E_I3C_1_CFG_CLK                   17
#define MBU_LSIO_E_I2C_2_CFG_CLK                   18
#define MBU_LSIO_E_I3C_2_CFG_CLK                   19
#define MBU_LSIO_E_I2C_3_CFG_CLK                   20
#define MBU_LSIO_E_I3C_3_CFG_CLK                   21
#define MBU_LSIO_E_I2C_4_CFG_CLK                   22
#define MBU_LSIO_E_I3C_4_CFG_CLK                   23
#define MBU_LSIO_E_SPI_0_CFG_CLK                   24
#define MBU_LSIO_E_UART_0_CFG_CLK                  25
#define MBU_LSIO_E_SPI_1_CFG_CLK                   26
#define MBU_LSIO_E_UART_1_CFG_CLK                  27
#define MBU_LSIO_E_GPIO_CLK                        28
#define MBU_AOSS_PG_AMB_I2C0_APB_CLK               0
#define MBU_AOSS_PG_AMB_I3C0_APB_CLK               1
#define MBU_AOSS_PG_AMB_I3C1_APB_CLK               2
#define MBU_AOSS_PG_AMB_I3C2_APB_CLK               3
#define MBU_AOSS_PG_AMB_UART0_APB_CLK              4
#define MBU_AOSS_PG_AMB_UART1_APB_CLK              5
#define MBU_AOSS_PG_AMB_UART2_APB_CLK              6
#define MBU_AOSS_PG_AMB_UART3_APB_CLK              7
#define MBU_AOSS_PG_AMB_UART4_APB_CLK              8
#define MBU_AOSS_PG_AMB_UART5_APB_CLK              9
#define MBU_AOSS_PG_AMB_SPI0_APB_CLK               10
#define MBU_AOSS_PG_AMB_SPI1_APB_CLK               11
#define MBU_AOSS_PG_AMB_SPI2_APB_CLK               12
#define MBU_AOSS_PG_AMB_SPI3_APB_CLK               13
#define MBU_AOSS_PG_AMB_SPI4_APB_CLK               14
#define MBU_AOSS_PG_AMB_SPI5_APB_CLK               15
#define MBU_AOSS_PG_AMB_SPI6_APB_CLK               16
#define MBU_AOSS_PG_AMB_TSPI_APB_CLK               17
#define MBU_AOSS_PG_AMB_I2C0_PERI_CLK              18
#define MBU_AOSS_PG_AMB_I3C0_PERI_CLK              19
#define MBU_AOSS_PG_AMB_I3C1_PERI_CLK              20
#define MBU_AOSS_PG_AMB_I3C2_PERI_CLK              21
#define MBU_AOSS_PG_AMB_UART0_PERI_CLK             22
#define MBU_AOSS_PG_AMB_UART1_PERI_CLK             23
#define MBU_AOSS_PG_AMB_UART2_PERI_CLK             24
#define MBU_AOSS_PG_AMB_UART3_PERI_CLK             25
#define MBU_AOSS_PG_AMB_UART4_PERI_CLK             26
#define MBU_AOSS_PG_AMB_UART5_PERI_CLK             27
#define MBU_AOSS_PG_AMB_SPI0_PERI_CLK              28
#define MBU_AOSS_PG_AMB_SPI1_PERI_CLK              29
#define MBU_AOSS_PG_AMB_SPI2_PERI_CLK              30
#define MBU_AOSS_PG_AMB_SPI3_PERI_CLK              31
#define MBU_AOSS_PG_AMB_SPI4_PERI_CLK              32
#define MBU_AOSS_PG_AMB_SPI5_PERI_CLK              33
#define MBU_AOSS_PG_AMB_SPI6_PERI_CLK              34
#define MBU_AOSS_PG_AMB_TSPI_PERI_CLK              35
#define MBU_CPUACC_GPDMA0_CLK                      0
#define MBU_CPUACC_GPDMA1_CLK                      1
#define MBU_CPUACC_GPDMA2_CLK                      2
#define MBU_CPUACC_GPDMA3_CLK                      3
#define MBU_CPUACC_GPDMA4_CLK                      4
#define MBU_CLK_PCIE_DPA_UART_CLK                  10
#define MBU_CPU_SSWRP_TSS_CLK                      0
#define MBU_CLK_HSIO_N_EBU_CORE                    33

#endif
