/* SPDX-License-Identifier: (GPL-2.0 OR BSD-3-Clause) */
/*
 * Wave6 series multi-standard codec IP - wave6 register definitions
 *
 * Copyright (C) 2025 CHIPS&MEDIA INC
 */

#ifndef __WAVE6_REGDEFINE_H__
#define __WAVE6_REGDEFINE_H__

#include <linux/bitfield.h>

enum wave6_command {
	W6_CMD_INIT_VPU		= 0x0001,
	W6_CMD_WAKEUP_VPU	= 0x0002,
	W6_CMD_SLEEP_VPU	= 0x0004,
	W6_CMD_CREATE_INSTANCE	= 0x0008,
	W6_CMD_FLUSH_INSTANCE	= 0x0010,
	W6_CMD_DESTROY_INSTANCE	= 0x0020,
	W6_CMD_INIT_SEQ		= 0x0040,
	W6_CMD_SET_FB		= 0x0080,
	W6_CMD_DEC_PIC		= 0x0100,
	W6_CMD_ENC_PIC		= 0x0100,
	W6_CMD_ENC_SET_PARAM	= 0x0200,
	W6_CMD_DEC_SET_DISP	= 0x0400,
	W6_CMD_INIT_WORK_BUF	= 0x1000,
	W6_CMD_QUERY		= 0x4000,
};

enum wave6_init_seq_option {
	W6_INIT_SEQ_OPT_NORMAL		= 1,
	W6_INIT_SEQ_OPT_W_THUMBNAIL	= 17,
};

enum wave6_set_param_option {
	W6_SET_PARAM_OPT_COMMON		= 0,
	W6_SET_PARAM_OPT_CHANGE_PARAM	= 1,
};

enum wave6_dec_pic_option {
	W6_DEC_PIC_OPT_NORMAL		= 0,
	W6_DEC_PIC_OPT_W_THUMBNAIL	= 16,
	W6_DEC_PIC_OPT_SKIP_NON_IRAP	= 17,
	W6_DEC_PIC_OPT_SKIP_NON_REF_PIC	= 19,
};

enum wave6_query_option {
	W6_QUERY_OPT_GET_VPU_INFO	= 0,
	W6_QUERY_OPT_GET_RESULT		= 2,
	W6_QUERY_OPT_GET_FLUSH_CMD_INFO	= 10,
};

enum wave6_interrupt_bit {
	W6_INT_BIT_INIT_VPU		= 0,
	W6_INT_BIT_WAKEUP_VPU		= 1,
	W6_INT_BIT_SLEEP_VPU		= 2,
	W6_INT_BIT_CREATE_INSTANCE	= 3,
	W6_INT_BIT_FLUSH_INSTANCE	= 4,
	W6_INT_BIT_DESTROY_INSTANCE	= 5,
	W6_INT_BIT_INIT_SEQ		= 6,
	W6_INT_BIT_SET_FB		= 7,
	W6_INT_BIT_DEC_PIC		= 8,
	W6_INT_BIT_ENC_PIC		= 8,
	W6_INT_BIT_ENC_SET_PARAM	= 9,
	W6_INT_BIT_SET_DISP		= 10,
	W6_INT_BIT_REQ_WORK_BUF		= 12,
	W6_INT_BIT_BSBUF_ERROR		= 15,
};

#define W6_REG_BASE	0x00000000
#define W6_CMD_REG_BASE	0x00000200
#define W6_CMD_REG_END	0x00000600

#define W6_VPU_VCPU_CUR_PC				(W6_REG_BASE + 0x0004)
#define W6_VPU_VINT_REASON_CLEAR			(W6_REG_BASE + 0x0034)
#define W6_VPU_HOST_INT_REQ				(W6_REG_BASE + 0x0038)
#define		HOST_INT_REQ_ON				BIT(0)
#define W6_VPU_VINT_CLEAR				(W6_REG_BASE + 0x003C)
#define		VINT_CLEAR				BIT(0)
#define W6_VPU_VPU_INT_STS				(W6_REG_BASE + 0x0044)
#define W6_VPU_VINT_ENABLE				(W6_REG_BASE + 0x0048)
#define W6_VPU_VINT_REASON				(W6_REG_BASE + 0x004C)
#define W6_VPU_REMAP_CTRL_GB				(W6_REG_BASE + 0x0060)
#define		REMAP_CTRL_ON				BIT(31)
#define		REMAP_CTRL_INDEX(x)			FIELD_PREP(GENMASK(15, 12), (x))
#define		REMAP_CTRL_PAGE_SIZE_ON			BIT(11)
#define		REMAP_CTRL_PAGE_SIZE(x)			FIELD_PREP(GENMASK(8, 0), ((x) >> 12))
#define W6_VPU_REMAP_VADDR_GB				(W6_REG_BASE + 0x0064)
#define W6_VPU_REMAP_PADDR_GB				(W6_REG_BASE + 0x0068)
#define W6_VPU_REMAP_CORE_START_GB			(W6_REG_BASE + 0x006C)
#define		REMAP_CORE_START_ON			BIT(0)
#define W6_VPU_BUSY_STATUS				(W6_REG_BASE + 0x0070)
#define		BUSY_STATUS_SET				BIT(0)
#define W6_VPU_RET_PRODUCT_CODE				(W6_REG_BASE + 0x0094)

/* COMMON */
#define W6_COMMAND_GB					(W6_REG_BASE + 0x104)
#define W6_COMMAND					(W6_REG_BASE + 0x200)
#define W6_QUERY_OPTION					(W6_REG_BASE + 0x204)
#define W6_CMD_INSTANCE_INFO				(W6_REG_BASE + 0x210)
#define		INSTANCE_INFO_CODEC_STD(x)		FIELD_PREP(GENMASK(31, 16), (x))
#define		INSTANCE_INFO_ID(x)			FIELD_PREP(GENMASK(15, 0), (x))
#define W6_CMD_INIT_VPU_SEC_AXI_BASE_CORE0		(W6_REG_BASE + 0x364)
#define W6_CMD_INIT_VPU_SEC_AXI_SIZE_CORE0		(W6_REG_BASE + 0x368)
#define W6_CMD_SET_WORK_BUF_ADDR			(W6_REG_BASE + 0x5F0)
#define W6_CMD_SET_WORK_BUF_SIZE			(W6_REG_BASE + 0x5F4)
#define		SET_WORK_BUF_SIZE_ACK			0
#define W6_RET_SUCCESS					(W6_REG_BASE + 0x208)
#define W6_RET_FAIL_REASON				(W6_REG_BASE + 0x20C)
#define W6_RET_INT_INSTANCE_INFO			(W6_REG_BASE + 0x21C)
#define		INT_INSTANCE_INFO_CLEAR			0
#define W6_RET_INSTANCE_ID				(W6_REG_BASE + 0x220)
#define W6_RET_CQ_IN_TICK				(W6_REG_BASE + 0x23C)
#define W6_RET_FW_RUN_TICK				(W6_REG_BASE + 0x240)
#define W6_RET_HW_RUN_TICK				(W6_REG_BASE + 0x244)
#define W6_RET_HW_DONE_TICK				(W6_REG_BASE + 0x248)
#define W6_RET_FW_DONE_TICK				(W6_REG_BASE + 0x24C)
#define W6_RET_RQ_OUT_TICK				(W6_REG_BASE + 0x250)

/* COMMON - QUERY : GET_VPU_INFO */
#define W6_RET_FW_VERSION				(W6_REG_BASE + 0x300)
#define W6_RET_PRODUCT_NAME				(W6_REG_BASE + 0x304)
#define W6_RET_PRODUCT_VERSION				(W6_REG_BASE + 0x308)
#define W6_RET_STD_DEF0					(W6_REG_BASE + 0x30C)
#define W6_RET_STD_DEF1					(W6_REG_BASE + 0x310)
#define		STD_DEF1_AVC_DEC(x)			FIELD_GET(GENMASK(3, 3), (x))
#define		STD_DEF1_HEVC_DEC(x)			FIELD_GET(GENMASK(2, 2), (x))
#define		STD_DEF1_AVC_ENC(x)			FIELD_GET(GENMASK(1, 1), (x))
#define		STD_DEF1_HEVC_ENC(x)			FIELD_GET(GENMASK(0, 0), (x))
#define W6_RET_CONF_FEATURE				(W6_REG_BASE + 0x314)
#define		CONF_FEATURE_AVC10BIT_ENC(x)		FIELD_GET(GENMASK(11, 11), (x))
#define		CONF_FEATURE_AVC10BIT_DEC(x)		FIELD_GET(GENMASK(9, 9), (x))
#define		CONF_FEATURE_HEVC10BIT_ENC(x)		FIELD_GET(GENMASK(3, 3), (x))
#define		CONF_FEATURE_HEVC10BIT_DEC(x)		FIELD_GET(GENMASK(1, 1), (x))
#define W6_RET_CONF_DATE				(W6_REG_BASE + 0x318)
#define W6_RET_CONF_HW_VERSION				(W6_REG_BASE + 0x31C)
#define W6_RET_CONF_TYPE				(W6_REG_BASE + 0x320)
#define W6_RET_FW_API_VERSION				(W6_REG_BASE + 0x32C)
#define W6_RET_SHA_ID					(W6_REG_BASE + 0x330)

/* COMMON - CREATE_INSTANCE */
#define W6_CMD_CREATE_INST_BS_PARAM			(W6_REG_BASE + 0x310)
#define W6_CMD_CREATE_INST_SRC_OPT			(W6_REG_BASE + 0x314)
#define W6_CMD_CREATE_INST_ADDR_EXT			(W6_REG_BASE + 0x318)
#define W6_CMD_CREATE_INST_DISP_MODE			(W6_REG_BASE + 0x31C)
#define W6_CMD_CREATE_INST_CORE_INFO			(W6_REG_BASE + 0x330)
#define		CREATE_INST_CORE_INFO_CQ_DEPTH(x)	FIELD_PREP(GENMASK(10, 8), (x))
#define		CREATE_INST_CORE_INFO_CORE_IDC(x)	FIELD_PREP(GENMASK(7, 4), (x))
#define		CREATE_INST_CORE_INFO_CORE_NUM(x)	FIELD_PREP(GENMASK(3, 0), (x))
#define W6_CMD_CREATE_INST_PRIORITY			(W6_REG_BASE + 0x334)
#define		CREATE_INST_PRIORITY_SECURITY_FLAG(x)	FIELD_PREP(GENMASK(8, 8), (x))
#define		CREATE_INST_PRIORITY_VALUE(x)		FIELD_PREP(GENMASK(4, 0), (x))
#define W6_CMD_CREATE_INST_TEMP_BASE			(W6_REG_BASE + 0x348)
#define W6_CMD_CREATE_INST_TEMP_SIZE			(W6_REG_BASE + 0x34C)
#define W6_CMD_CREATE_INST_AR_TABLE_BASE		(W6_REG_BASE + 0x358)
#define W6_CMD_CREATE_INST_TIMEOUT_CYCLE_COUNT		(W6_REG_BASE + 0x3A8)

/* COMMON - SET_FB */
#define W6_CMD_SET_FB_OPTION				(W6_REG_BASE + 0x204)
#define		SET_FB_OPTION_ENDIAN(x)			FIELD_PREP(GENMASK(19, 16), (x))
#define		SET_FB_OPTION_END			BIT(4)
#define		SET_FB_OPTION_START			BIT(3)
#define W6_CMD_SET_FB_PIC_INFO				(W6_REG_BASE + 0x300)
#define		SET_FB_PIC_INFO_C_FMT_IDC(x)		FIELD_PREP(GENMASK(26, 25), (x))
#define		SET_FB_PIC_INFO_L_BIT_DEPTH(x)		FIELD_PREP(GENMASK(24, 21), (x))
#define		SET_FB_PIC_INFO_C_BIT_DEPTH(x)		FIELD_PREP(GENMASK(20, 17), (x))
#define		SET_FB_PIC_INFO_STRIDE(x)		FIELD_PREP(GENMASK(15, 0), (x))
#define W6_CMD_SET_FB_PIC_SIZE				(W6_REG_BASE + 0x304)
#define		SET_FB_PIC_SIZE_WIDTH(x)		FIELD_PREP(GENMASK(31, 16), (x))
#define		SET_FB_PIC_SIZE_HEIGHT(x)		FIELD_PREP(GENMASK(15, 0), (x))
#define W6_CMD_SET_FB_NUM				(W6_REG_BASE + 0x308)
#define		SET_FB_NUM_FBC_START_IDX(x)		FIELD_PREP(GENMASK(28, 24), (x))
#define		SET_FB_NUM_FBC_END_IDX(x)		FIELD_PREP(GENMASK(20, 16), (x))
#define		SET_FB_NUM_MV_COL_START_IDX(x)		FIELD_PREP(GENMASK(9, 5), (x))
#define		SET_FB_NUM_MV_COL_END_IDX(x)		FIELD_PREP(GENMASK(4, 0), (x))
#define W6_CMD_SET_FB_FBC_STRIDE			(W6_REG_BASE + 0x30C)
#define		SET_FB_FBC_STRIDE_L(x)			FIELD_PREP(GENMASK(31, 16), (x))
#define		SET_FB_FBC_STRIDE_C(x)			FIELD_PREP(GENMASK(15, 0), (x))

/* W6_CMD_SET_FB_FBC_Y(x)
 * Address range: 0x310, 0x328, ..., 0x478 (step = 0x18)
 */
#define W6_CMD_SET_FB_FBC_Y(x)				(W6_REG_BASE + 0x310 + ((x) * 0x18))

/* W6_CMD_SET_FB_FBC_C(x)
 * Address range: 0x314, 0x32C, ..., 0x47C (step = 0x18)
 */
#define W6_CMD_SET_FB_FBC_C(x)				(W6_REG_BASE + 0x314 + ((x) * 0x18))

/* W6_CMD_SET_FB_FBC_Y_OFFSET(x)
 * Address range: 0x318, 0x330, ..., 0x480 (step = 0x18)
 */
#define W6_CMD_SET_FB_FBC_Y_OFFSET(x)			(W6_REG_BASE + 0x318 + ((x) * 0x18))

/* W6_CMD_SET_FB_FBC_C_OFFSET(x)
 * Address range: 0x31C, 0x334, ..., 0x484 (step = 0x18)
 */
#define W6_CMD_SET_FB_FBC_C_OFFSET(x)			(W6_REG_BASE + 0x31C + ((x) * 0x18))

/* W6_CMD_SET_FB_MV_COL(x)
 * Address range: 0x320, 0x338, ..., 0x488 (step = 0x18)
 */
#define W6_CMD_SET_FB_MV_COL(x)				(W6_REG_BASE + 0x320 + ((x) * 0x18))

/* W6_CMD_SET_FB_SUB_SAMPLED(x)
 * Address range: 0x324, 0x33C, ..., 0x48C (step = 0x18)
 */
#define W6_CMD_SET_FB_SUB_SAMPLED(x)			(W6_REG_BASE + 0x324 + ((x) * 0x18))
#define W6_CMD_SET_FB_DEFAULT_CDF			(W6_REG_BASE + 0x494)
#define W6_CMD_SET_FB_SEGMAP				(W6_REG_BASE + 0x498)
#define W6_CMD_SET_FB_MV_COL_PRE_ENT			(W6_REG_BASE + 0x4DC)

/* W6_CMD_SET_FB_FBC_CR(x)
 * Address range: 0x4F0, 0x4F8, ..., 0x568 (step = 0x8)
 */
#define W6_CMD_SET_FB_FBC_CR(x)				(W6_REG_BASE + 0x4F0 + ((x) * 0x8))

/* W6_CMD_SET_FB_FBC_CR_OFFSET(x)
 * Address range: 0x4F4, 0x4FC, ..., 0x56C (step = 0x8)
 */
#define W6_CMD_SET_FB_FBC_CR_OFFSET(x)			(W6_REG_BASE + 0x4F4 + ((x) * 0x8))

/* DECODER - INIT_SEQ */
#define W6_CMD_DEC_INIT_SEQ_OPTION			(W6_REG_BASE + 0x204)
#define		INIT_SEQ_OPTION_MODE(x)			FIELD_PREP(GENMASK(5, 0), (x))
#define W6_CMD_DEC_INIT_SEQ_BS_RD_PTR			(W6_REG_BASE + 0x300)
#define W6_CMD_DEC_INIT_SEQ_BS_WR_PTR			(W6_REG_BASE + 0x304)
#define W6_CMD_DEC_INIT_SEQ_BS_OPTION			(W6_REG_BASE + 0x308)

/* DECODER - SET_DISP */
#define W6_CMD_DEC_SET_DISP_OPTION			(W6_REG_BASE + 0x204)
#define		SET_DISP_OPTION_ENDIAN(x)		FIELD_PREP(GENMASK(19, 16), (x))
#define W6_CMD_DEC_SET_DISP_COMMON_PIC_INFO		(W6_REG_BASE + 0x300)
#define		SET_DISP_COMMON_PIC_INFO_BWB_ON		BIT(28)
#define		SET_DISP_COMMON_PIC_INFO_C_FMT_IDC(x)	FIELD_PREP(GENMASK(25, 24), (x))
#define		SET_DISP_COMMON_PIC_INFO_PIXEL_ORDER(x)	FIELD_PREP(GENMASK(23, 23), (x))
#define		SET_DISP_COMMON_PIC_INFO_OUT_MODE(x)	FIELD_PREP(GENMASK(22, 20), (x))
#define		SET_DISP_COMMON_PIC_INFO_OUT_FMT(x)	FIELD_PREP(GENMASK(18, 16), (x))
#define		SET_DISP_COMMON_PIC_INFO_STRIDE(x)	FIELD_PREP(GENMASK(15, 0), (x))
#define W6_CMD_DEC_SET_DISP_PIC_SIZE			(W6_REG_BASE + 0x304)
#define		SET_DISP_PIC_SIZE_WIDTH(x)		FIELD_PREP(GENMASK(31, 16), (x))
#define		SET_DISP_PIC_SIZE_HEIGHT(x)		FIELD_PREP(GENMASK(15, 0), (x))
#define W6_CMD_DEC_SET_DISP_PIC_INFO			(W6_REG_BASE + 0x308)
#define		SET_DISP_PIC_INFO_L_BIT_DEPTH(x)	FIELD_PREP(GENMASK(25, 22), (x))
#define		SET_DISP_PIC_INFO_C_BIT_DEPTH(x)	FIELD_PREP(GENMASK(21, 18), (x))
#define		SET_DISP_PIC_INFO_C_FMT_IDC(x)		FIELD_PREP(GENMASK(17, 16), (x))
#define W6_CMD_DEC_SET_DISP_Y_BASE			(W6_REG_BASE + 0x30C)
#define W6_CMD_DEC_SET_DISP_CB_BASE			(W6_REG_BASE + 0x310)
#define W6_CMD_DEC_SET_DISP_CR_BASE			(W6_REG_BASE + 0x314)
#define W6_CMD_DEC_SET_DISP_SCL_PARAM			(W6_REG_BASE + 0x318)
#define W6_CMD_DEC_SET_DISP_SCL_PIC_SIZE		(W6_REG_BASE + 0x31C)
#define		SET_DISP_SCL_PIC_SIZE_WIDTH(x)		FIELD_PREP(GENMASK(31, 16), (x))
#define		SET_DISP_SCL_PIC_SIZE_HEIGHT(x)		FIELD_PREP(GENMASK(15, 0), (x))

/* DECODER - DEC_PIC */
#define W6_CMD_DEC_PIC_OPTION				(W6_REG_BASE + 0x204)
#define		DEC_PIC_OPTION_MODE(x)			FIELD_PREP(GENMASK(5, 0), (x))
#define W6_CMD_DEC_PIC_BS_RD_PTR			(W6_REG_BASE + 0x300)
#define W6_CMD_DEC_PIC_BS_WR_PTR			(W6_REG_BASE + 0x304)
#define W6_CMD_DEC_PIC_BS_OPTION			(W6_REG_BASE + 0x308)
#define		DEC_PIC_BS_OPTION_STREAM_END(x)		FIELD_PREP(GENMASK(1, 1), (x))
#define		DEC_PIC_BS_OPTION_EXPLICIT_END_ON	BIT(0)
#define W6_CMD_DEC_PIC_SEC_AXI				(W6_REG_BASE + 0x30C)
#define		DEC_PIC_SEC_AXI_IP_ENABLE(x)		FIELD_PREP(GENMASK(1, 1), (x))
#define		DEC_PIC_SEC_AXI_LF_ENABLE(x)		FIELD_PREP(GENMASK(0, 0), (x))
#define W6_CMD_DEC_PIC_SEQ_CHANGE_ENABLE_FLAG		(W6_REG_BASE + 0x310)
#define W6_CMD_DEC_PIC_TEMPORAL_ID_PLUS1		(W6_REG_BASE + 0x318)
#define		DEC_PIC_TEMPORAL_ID_PLUS1_SPATIAL(x)	FIELD_PREP(GENMASK(11, 9), (x))
#define		DEC_PIC_TEMPORAL_ID_PLUS1(x)		FIELD_PREP(GENMASK(7, 0), (x))
#define W6_CMD_DEC_PIC_TIMESTAMP_LOW			(W6_REG_BASE + 0x354)
#define W6_CMD_DEC_PIC_TIMESTAMP_HIGH			(W6_REG_BASE + 0x358)

/* DECODER - QUERY : GET_RESULT */
#define W6_RET_DEC_BS_RD_PTR				(W6_REG_BASE + 0x30C)
#define W6_RET_DEC_SEQ_PARAM				(W6_REG_BASE + 0x310)
#define		DEC_SEQ_PARAM_TIER(x)			FIELD_GET(GENMASK(29, 29), (x))
#define		DEC_SEQ_PARAM_PROFILE(x)		FIELD_GET(GENMASK(28, 24), (x))
#define		PROFILE_H264_BP				2
#define		PROFILE_H264_HP				4
#define		PROFILE_H264_MP				13
#define		PROFILE_H264_HIGH10			14
#define		PROFILE_H264_EXTENDED			24
#define		DEC_SEQ_PARAM_PROFILE_COMPATIBILITY(x)	FIELD_GET(GENMASK(19, 12), (x))
#define		PROFILE_COMPATIBILITY_MAIN		BIT(1)
#define		PROFILE_COMPATIBILITY_MAIN10		BIT(2)
#define		PROFILE_COMPATIBILITY_STILL_PICTURE	BIT(3)
#define		DEC_SEQ_PARAM_LEVEL(x)			FIELD_GET(GENMASK(7, 0), (x))
#define W6_RET_DEC_COLOR_SAMPLE				(W6_REG_BASE + 0x314)
#define		DEC_COLOR_SAMPLE_ASPECT_RATIO_IDC(x)	FIELD_GET(GENMASK(23, 16), (x))
#define		DEC_COLOR_SAMPLE_C_FMT_IDC(x)		FIELD_GET(GENMASK(11, 8), (x))
#define		DEC_COLOR_SAMPLE_C_BIT_DEPTH(x)		FIELD_GET(GENMASK(7, 4), (x))
#define		DEC_COLOR_SAMPLE_L_BIT_DEPTH(x)		FIELD_GET(GENMASK(3, 0), (x))
#define W6_RET_DEC_ASPECT_RATIO				(W6_REG_BASE + 0x318)
#define W6_RET_DEC_BIT_RATE				(W6_REG_BASE + 0x31C)
#define W6_RET_DEC_FRAME_RATE_NR			(W6_REG_BASE + 0x320)
#define W6_RET_DEC_FRAME_RATE_DR			(W6_REG_BASE + 0x324)
#define W6_RET_DEC_NUM_REQUIRED_FBC_FB			(W6_REG_BASE + 0x328)
#define W6_RET_DEC_NUM_REORDER_DELAY			(W6_REG_BASE + 0x32C)
#define W6_RET_DEC_NOTIFICATION				(W6_REG_BASE + 0x334)
#define W6_RET_DEC_PIC_SIZE				(W6_REG_BASE + 0x33C)
#define		DEC_PIC_SIZE_WIDTH(x)			FIELD_GET(GENMASK(31, 16), (x))
#define		DEC_PIC_SIZE_HEIGHT(x)			FIELD_GET(GENMASK(15, 0), (x))
#define W6_RET_DEC_CROP_TOP_BOTTOM			(W6_REG_BASE + 0x340)
#define		DEC_CROP_TOP(x)				FIELD_GET(GENMASK(31, 16), (x))
#define		DEC_CROP_BOTTOM(x)			FIELD_GET(GENMASK(15, 0), (x))
#define W6_RET_DEC_CROP_LEFT_RIGHT			(W6_REG_BASE + 0x344)
#define		DEC_CROP_LEFT(x)			FIELD_GET(GENMASK(31, 16), (x))
#define		DEC_CROP_RIGHT(x)			FIELD_GET(GENMASK(15, 0), (x))
#define W6_RET_DEC_AU_START_POS				(W6_REG_BASE + 0x348)
#define W6_RET_DEC_AU_END_POS				(W6_REG_BASE + 0x34C)
#define W6_RET_DEC_PIC_TYPE				(W6_REG_BASE + 0x350)
#define		DEC_PIC_TYPE_CTU_SIZE(x)		(16 << FIELD_GET(GENMASK(11, 10), (x)))
#define		DEC_PIC_TYPE_NAL_UNIT_TYPE(x)		FIELD_GET(GENMASK(9, 4), (x))
#define		DEC_PIC_TYPE_B				BIT(2)
#define		DEC_PIC_TYPE_P				BIT(1)
#define		DEC_PIC_TYPE_I				BIT(0)
#define W6_RET_DEC_PIC_POC				(W6_REG_BASE + 0x354)
#define W6_RET_DEC_RECOVERY_POINT			(W6_REG_BASE + 0x358)
#define W6_RET_DEC_DECODED_ADDR				(W6_REG_BASE + 0x360)
#define W6_RET_DEC_DISPLAY_ADDR				(W6_REG_BASE + 0x364)
#define W6_RET_DEC_ERR_CTB_NUM				(W6_REG_BASE + 0x370)
#define W6_RET_DEC_DISPLAY_FLAG				(W6_REG_BASE + 0x3A8)
#define W6_RET_DEC_RELEASE_IDC				(W6_REG_BASE + 0x3AC)
#define W6_RET_DEC_DISP_IDC				(W6_REG_BASE + 0x3B0)
#define W6_RET_DEC_STREAM_END				(W6_REG_BASE + 0x3C0)
#define W6_RET_DEC_DECODED_FLAG				(W6_REG_BASE + 0x3C4)
#define W6_RET_DEC_WARN_INFO				(W6_REG_BASE + 0x3CC)
#define W6_RET_DEC_ERR_INFO				(W6_REG_BASE + 0x3D0)
#define W6_RET_DEC_DECODING_SUCCESS			(W6_REG_BASE + 0x3D4)
#define W6_RET_DEC_TIMESTAMP_LOW			(W6_REG_BASE + 0x3D8)
#define W6_RET_DEC_TIMESTAMP_HIGH			(W6_REG_BASE + 0x3DC)
#define W6_RET_DEC_LAST_FRAME_FLAG			(W6_REG_BASE + 0x3E0)
#define W6_RET_DEC_NUM_REQUIRED_COL_BUF			(W6_REG_BASE + 0x3E4)

/* W6_RET_DEC_DISP_LINEAR_ADDR(x)
 * Address range: 0x3E8, 0x3EC, ..., 0x460 (step = 0x4)
 */
#define W6_RET_DEC_DISP_LINEAR_ADDR(x)			(W6_REG_BASE + 0x3E8 + ((x) * 0x4))
#define W6_RET_DEC_COLOR_CONFIG				(W6_REG_BASE + 0x57C)
#define		DEC_COLOR_CONFIG_COLOR_RANGE(x)		FIELD_GET(GENMASK(25, 25), (x))
#define		DEC_COLOR_CONFIG_MATRIX_COEFF(x)	FIELD_GET(GENMASK(24, 17), (x))
#define		DEC_COLOR_CONFIG_TRANS_CHAR(x)		FIELD_GET(GENMASK(16, 9), (x))
#define		DEC_COLOR_CONFIG_COLOR_PRIMARIES(x)	FIELD_GET(GENMASK(8, 1), (x))
#define		DEC_COLOR_CONFIG_COLOR_PRESENT(x)	FIELD_GET(GENMASK(0, 0), (x))

/* DECODER - QUERY : GET_FLUSH_CMD_INFO */

/* W6_RET_DEC_FLUSH_CMD_DISP_ADDR(x)
 * Address range: 0x300, 0x304, ..., 0x378 (step = 0x4)
 */
#define W6_RET_DEC_FLUSH_CMD_DISP_ADDR(x)		(W6_REG_BASE + 0x300 + ((x) * 0x4))
#define W6_RET_DEC_FLUSH_CMD_BUF_STATE_UNUSED_IDC	(W6_REG_BASE + 0x57C)
#define W6_RET_DEC_FLUSH_CMD_BUF_STATE_USED_IDC		(W6_REG_BASE + 0x580)
#define W6_RET_DEC_FLUSH_CMD_BUF_STATE_USING_IDC	(W6_REG_BASE + 0x584)

/* ENCODER - SET_PARAM */
#define W6_CMD_ENC_SET_PARAM_OPTION			(W6_REG_BASE + 0x204)
#define W6_CMD_ENC_SET_PARAM_ENABLE			(W6_REG_BASE + 0x300)
#define		SET_PARAM_ENABLE_RC_TARGET_RATE		BIT(10)
#define W6_CMD_ENC_SET_PARAM_SRC_SIZE			(W6_REG_BASE + 0x304)
#define		SET_PARAM_SRC_SIZE_HEIGHT(x)		FIELD_PREP(GENMASK(31, 16), (x))
#define		SET_PARAM_SRC_SIZE_WIDTH(x)		FIELD_PREP(GENMASK(15, 0), (x))
#define W6_CMD_ENC_SET_PARAM_CUSTOM_MAP_ENDIAN		(W6_REG_BASE + 0x308)
#define W6_CMD_ENC_SET_PARAM_SPS			(W6_REG_BASE + 0x30C)
#define		SET_PARAM_SPS_DEFAULT_SCALING_LIST(x)	FIELD_PREP(GENMASK(31, 31), (x))
#define		SET_PARAM_SPS_STILL_PICTURE(x)		FIELD_PREP(GENMASK(30, 30), (x))
#define		SET_PARAM_SPS_AUTO_LEVEL_ADJUSTING_ON	BIT(28)
#define		SET_PARAM_SPS_STRONG_INTRA_SMOOTHING(x)	FIELD_PREP(GENMASK(27, 27), (x))
#define		SET_PARAM_SPS_INTRA_TRANSFORM_SKIP_ON	BIT(25)
#define		SET_PARAM_SPS_SAMPLE_ADAPTIVE_OFFSET(x)	FIELD_PREP(GENMASK(24, 24), (x))
#define		SET_PARAM_SPS_TEMPORAL_MVP(x)		FIELD_PREP(GENMASK(23, 23), (x))
#define		SET_PARAM_SPS_LONGTERM_REFERENCE(x)	FIELD_PREP(GENMASK(21, 21), (x))
#define		SET_PARAM_SPS_C_FMT_IDC(x)		FIELD_PREP(GENMASK(20, 19), (x))
#define		SET_PARAM_SPS_BIT_DEPTH(x)		FIELD_PREP(GENMASK(18, 14), (x))
#define		SET_PARAM_SPS_TIER(x)			FIELD_PREP(GENMASK(13, 12), (x))
#define		SET_PARAM_SPS_LEVEL(x)			FIELD_PREP(GENMASK(11, 3), (x))
#define		SET_PARAM_SPS_PROFILE(x)		FIELD_PREP(GENMASK(2, 0), (x))
#define W6_CMD_ENC_SET_PARAM_PPS			(W6_REG_BASE + 0x310)
#define		SET_PARAM_PPS_ENTROPY_CODING_MODE(x)	FIELD_PREP(GENMASK(30, 30), (x))
#define		SET_PARAM_PPS_TRANSFORM8X8(x)		FIELD_PREP(GENMASK(29, 29), (x))
#define		SET_PARAM_PPS_CR_QP_OFFSET(x)		FIELD_PREP(GENMASK(23, 19), (x))
#define		SET_PARAM_PPS_CB_QP_OFFSET(x)		FIELD_PREP(GENMASK(18, 14), (x))
#define		SET_PARAM_PPS_TC_OFFSET_DIV2(x)		FIELD_PREP(GENMASK(13, 10), (x))
#define		SET_PARAM_PPS_BETA_OFFSET_DIV2(x)	FIELD_PREP(GENMASK(9, 6), (x))
#define		SET_PARAM_PPS_DEBLOCKING_FILTER(x)	FIELD_PREP(GENMASK(5, 5), (x))
#define		SET_PARAM_PPS_LF_SLICE_BOUNDARY(x)	FIELD_PREP(GENMASK(2, 2), (x))
#define		SET_PARAM_PPS_CONST_INTRA_PREDICTION(x)	FIELD_PREP(GENMASK(1, 1), (x))
#define W6_CMD_ENC_SET_PARAM_GOP			(W6_REG_BASE + 0x314)
#define		SET_PARAM_GOP_TEMP_LAYER_CNT(x)		FIELD_PREP(GENMASK(19, 16), (x))
#define		SET_PARAM_GOP_TEMP_LAYER3_QP_ENABLE(x)	FIELD_PREP(GENMASK(11, 11), (x))
#define		SET_PARAM_GOP_TEMP_LAYER2_QP_ENABLE(x)	FIELD_PREP(GENMASK(10, 10), (x))
#define		SET_PARAM_GOP_TEMP_LAYER1_QP_ENABLE(x)	FIELD_PREP(GENMASK(9, 9), (x))
#define		SET_PARAM_GOP_TEMP_LAYER0_QP_ENABLE(x)	FIELD_PREP(GENMASK(8, 8), (x))
#define		SET_PARAM_GOP_PRESET_IDX(x)		FIELD_PREP(GENMASK(7, 0), (x))
#define W6_CMD_ENC_SET_PARAM_INTRA			(W6_REG_BASE + 0x318)
#define		SET_PARAM_INTRA_PERIOD(x)		FIELD_PREP(GENMASK(31, 16), (x))
#define		SET_PARAM_INTRA_HEADER_MODE(x)		FIELD_PREP(GENMASK(10, 9), (x))
#define		SET_PARAM_INTRA_QP(x)			FIELD_PREP(GENMASK(8, 3), (x))
#define		SET_PARAM_INTRA_REFRESH_TYPE(x)		FIELD_PREP(GENMASK(2, 0), (x))

/* W6_CMD_ENC_SET_PARAM_INTRA for AVC specific fields */
#define		SET_PARAM_INTRA_HEADER_MODE_AVC(x)	FIELD_PREP(GENMASK(29, 28), (x))
#define		SET_PARAM_INTRA_IDR_PERIOD_AVC(x)	FIELD_PREP(GENMASK(27, 17), (x))
#define		SET_PARAM_INTRA_PERIOD_AVC(x)		FIELD_PREP(GENMASK(16, 6), (x))
#define		SET_PARAM_INTRA_QP_AVC(x)		FIELD_PREP(GENMASK(5, 0), (x))
#define W6_CMD_ENC_SET_PARAM_CONF_WIN0			(W6_REG_BASE + 0x31C)
#define		SET_PARAM_CONF_WIN0_BOTTOM(x)		FIELD_PREP(GENMASK(31, 16), (x))
#define		SET_PARAM_CONF_WIN0_TOP(x)		FIELD_PREP(GENMASK(15, 0), (x))
#define W6_CMD_ENC_SET_PARAM_CONF_WIN1			(W6_REG_BASE + 0x320)
#define		SET_PARAM_CONF_WIN1_RIGHT(x)		FIELD_PREP(GENMASK(31, 16), (x))
#define		SET_PARAM_CONF_WIN1_LEFT(x)		FIELD_PREP(GENMASK(15, 0), (x))
#define W6_CMD_ENC_SET_PARAM_RDO			(W6_REG_BASE + 0x324)
#define		SET_PARAM_RDO_CUSTOM_LAMBDA(x)		FIELD_PREP(GENMASK(22, 22), (x))
#define		SET_PARAM_RDO_ME_SEARCH_CENTER_ON	BIT(21)
#define		SET_PARAM_RDO_QROUND_OFFSET(x)		FIELD_PREP(GENMASK(17, 17), (x))
#define		SET_PARAM_RDO_ADAPTIVE_ROUND_ON		BIT(3)
#define		SET_PARAM_RDO_HVS_QP(x)			FIELD_PREP(GENMASK(2, 2), (x))
#define W6_CMD_ENC_SET_PARAM_SLICE			(W6_REG_BASE + 0x328)
#define		SET_PARAM_SLICE_ARGUMENT(x)		FIELD_PREP(GENMASK(31, 3), (x))
#define		SET_PARAM_SLICE_MODE(x)			FIELD_PREP(GENMASK(2, 0), (x))
#define W6_CMD_ENC_SET_PARAM_INTRA_REFRESH		(W6_REG_BASE + 0x32C)
#define		SET_PARAM_INTRA_REFRESH_ARGUMENT(x)	FIELD_PREP(GENMASK(31, 16), (x))
#define		SET_PARAM_INTRA_REFRESH_MODE(x)		FIELD_PREP(GENMASK(2, 0), (x))
#define W6_CMD_ENC_SET_PARAM_INTRA_QP			(W6_REG_BASE + 0x330)
#define		SET_PARAM_INTRA_QP_MAX(x)		FIELD_PREP(GENMASK(11, 6), (x))
#define		SET_PARAM_INTRA_QP_MIN(x)		FIELD_PREP(GENMASK(5, 0), (x))
#define W6_CMD_ENC_SET_PARAM_RC_FRAME_RATE		(W6_REG_BASE + 0x334)
#define W6_CMD_ENC_SET_PARAM_RC_TARGET_RATE		(W6_REG_BASE + 0x338)
#define W6_CMD_ENC_SET_PARAM_RC				(W6_REG_BASE + 0x33C)
#define		SET_PARAM_RC_UPDATE_SPEED(x)		FIELD_PREP(GENMASK(31, 24), (x))
#define		SET_PARAM_RC_INITIAL_LEVEL(x)		FIELD_PREP(GENMASK(23, 20), (x))
#define		SET_PARAM_RC_INITIAL_QP(x)		FIELD_PREP(GENMASK(19, 14), (x))
#define		SET_PARAM_RC_MODE(x)			FIELD_PREP(GENMASK(13, 13), (x))
#define		SET_PARAM_RC_PIC_LEVEL_MAX_DELTA_QP(x)	FIELD_PREP(GENMASK(12, 7), (x))
#define		SET_PARAM_RC_VBV_OVERFLOW_DROP_FRAME(x)	FIELD_PREP(GENMASK(3, 3), (x))
#define		SET_PARAM_RC_CU_LEVEL_ENABLE(x)		FIELD_PREP(GENMASK(1, 1), (x))
#define		SET_PARAM_RC_ENABLE(x)			FIELD_PREP(GENMASK(0, 0), (x))
#define W6_CMD_ENC_SET_PARAM_HVS			(W6_REG_BASE + 0x340)
#define		SET_PARAM_HVS_MAX_DELTA_QP(x)		FIELD_PREP(GENMASK(17, 12), (x))
#define		SET_PARAM_HVS_QP_SCALE(x)		FIELD_PREP(GENMASK(3, 0), (x))
#define W6_CMD_ENC_SET_PARAM_RC_MAX_BITRATE		(W6_REG_BASE + 0x344)
#define W6_CMD_ENC_SET_PARAM_RC_VBV_BUFFER_SIZE		(W6_REG_BASE + 0x348)
#define W6_CMD_ENC_SET_PARAM_INTER_QP			(W6_REG_BASE + 0x34C)
#define		SET_PARAM_INTER_QP_MAX_B(x)		FIELD_PREP(GENMASK(23, 18), (x))
#define		SET_PARAM_INTER_QP_MIN_B(x)		FIELD_PREP(GENMASK(17, 12), (x))
#define		SET_PARAM_INTER_QP_MAX_P(x)		FIELD_PREP(GENMASK(11, 6), (x))
#define		SET_PARAM_INTER_QP_MIN_P(x)		FIELD_PREP(GENMASK(5, 0), (x))
#define W6_CMD_ENC_SET_PARAM_ROT			(W6_REG_BASE + 0x350)
#define		SET_PARAM_ROT_MIRH			BIT(4)
#define		SET_PARAM_ROT_MIRV			BIT(3)
#define		SET_PARAM_ROT_270			FIELD_PREP(GENMASK(2, 1), 3)
#define		SET_PARAM_ROT_180			FIELD_PREP(GENMASK(2, 1), 2)
#define		SET_PARAM_ROT_90			FIELD_PREP(GENMASK(2, 1), 1)
#define		SET_PARAM_ROT_ENABLE			BIT(0)
#define W6_CMD_ENC_SET_PARAM_NUM_UNITS_IN_TICK		(W6_REG_BASE + 0x354)
#define W6_CMD_ENC_SET_PARAM_TIME_SCALE			(W6_REG_BASE + 0x358)
#define W6_CMD_ENC_SET_PARAM_NUM_TICKS_POC_DIFF_ONE	(W6_REG_BASE + 0x35C)
#define W6_CMD_ENC_SET_PARAM_MAX_INTRA_PIC_BIT		(W6_REG_BASE + 0x360)
#define W6_CMD_ENC_SET_PARAM_MAX_INTER_PIC_BIT		(W6_REG_BASE + 0x364)
#define W6_CMD_ENC_SET_PARAM_BG				(W6_REG_BASE + 0x36C)
#define		SET_PARAM_BG_DELTA_QP(x)		FIELD_PREP(GENMASK(29, 24), (x))
#define		SET_PARAM_BG_THRESHOLD_MEAN_DIFF(x)	FIELD_PREP(GENMASK(17, 10), (x))
#define		SET_PARAM_BG_THRESHOLD_MAX_DIFF(x)	FIELD_PREP(GENMASK(9, 1), (x))
#define		SET_PARAM_BG_ENABLE(x)			FIELD_PREP(GENMASK(0, 0), (x))
#define W6_CMD_ENC_SET_PARAM_NON_VCL_PARAM		(W6_REG_BASE + 0x370)
#define		SET_PARAM_NON_VCL_PARAM_ENCODE_VUI	BIT(1)
#define W6_CMD_ENC_SET_PARAM_VUI_RBSP_ADDR		(W6_REG_BASE + 0x374)
#define W6_CMD_ENC_SET_PARAM_HRD_RBSP_ADDR		(W6_REG_BASE + 0x378)
#define W6_CMD_ENC_SET_PARAM_QROUND_OFFSET		(W6_REG_BASE + 0x380)
#define		SET_PARAM_QROUND_OFFSET_INTER(x)	FIELD_PREP(GENMASK(23, 13), (x))
#define		SET_PARAM_QROUND_OFFSET_INTRA(x)	FIELD_PREP(GENMASK(12, 2), (x))
#define W6_CMD_ENC_SET_PARAM_QUANT1			(W6_REG_BASE + 0x384)
#define W6_CMD_ENC_SET_PARAM_QUANT2			(W6_REG_BASE + 0x388)
#define		SET_PARAM_QUANT2_LAMBDA_DQP_INTER(x)	FIELD_PREP(GENMASK(19, 14), (x))
#define		SET_PARAM_QUANT2_LAMBDA_DQP_INTRA(x)	FIELD_PREP(GENMASK(13, 8), (x))
#define W6_CMD_ENC_SET_PARAM_CUSTOM_GOP			(W6_REG_BASE + 0x38C)

/* W6_CMD_ENC_SET_PARAM_CUSTOM_GOP_PIC(x)
 * Address range: 0x390, 0x394, ..., 0x3AC (step = 0x4)
 */
#define W6_CMD_ENC_SET_PARAM_CUSTOM_GOP_PIC(x)		(W6_REG_BASE + 0x390 + ((x) * 0x4))
#define		SET_PARAM_CUSTOM_GOP_PIC_TEMP_ID(x)	FIELD_PREP(GENMASK(29, 26), (x))
#define		SET_PARAM_CUSTOM_GOP_PIC_REF1_POC(x)	FIELD_PREP(GENMASK(25, 20), (x))
#define		SET_PARAM_CUSTOM_GOP_PIC_REF0_POC(x)	FIELD_PREP(GENMASK(19, 14), (x))
#define		SET_PARAM_CUSTOM_GOP_PIC_MULTI_REF_P(x)	FIELD_PREP(GENMASK(13, 13), (x))
#define		SET_PARAM_CUSTOM_GOP_PIC_QP(x)		FIELD_PREP(GENMASK(12, 7), (x))
#define		SET_PARAM_CUSTOM_GOP_PIC_POC_OFFSET(x)	FIELD_PREP(GENMASK(6, 2), (x))
#define		SET_PARAM_CUSTOM_GOP_PIC_TYPE(x)	FIELD_PREP(GENMASK(1, 0), (x))
#define W6_CMD_ENC_SET_PARAM_TILE_PARAM			(W6_REG_BASE + 0x3D0)

/* W6_CMD_ENC_SET_PARAM_CUSTOM_LAMBDA(x)
 * Address range: 0x3D4, 0x3D8, ..., 0x4A0 (step = 0x4)
 */
#define W6_CMD_ENC_SET_PARAM_CUSTOM_LAMBDA(x)		(W6_REG_BASE + 0x3D4 + ((x) * 0x4))
#define		SET_PARAM_CUSTOM_LAMBDA_SSD(x)		FIELD_PREP(GENMASK(20, 7), (x))
#define		SET_PARAM_CUSTOM_LAMBDA_SAD(x)		FIELD_PREP(GENMASK(6, 0), (x))

/* W6_CMD_ENC_SET_PARAM_TEMP_LAYER_QP(x)
 * Address range: 0x4A4, 0x4A8, ..., 0x4B0 (step = 0x4)
 */
#define W6_CMD_ENC_SET_PARAM_TEMP_LAYER_QP(x)		(W6_REG_BASE + 0x4A4 + ((x) * 0x4))
#define		SET_PARAM_TEMP_LAYER_QP_B(x)		FIELD_PREP(GENMASK(17, 12), (x))
#define		SET_PARAM_TEMP_LAYER_QP_P(x)		FIELD_PREP(GENMASK(11, 6), (x))
#define		SET_PARAM_TEMP_LAYER_QP_I(x)		FIELD_PREP(GENMASK(5, 0), (x))
#define W6_CMD_ENC_SET_PARAM_SCALER_SIZE		(W6_REG_BASE + 0x4B4)
#define		SET_PARAM_SCALER_SIZE_HEIGHT(x)		FIELD_PREP(GENMASK(31, 16), (x))
#define		SET_PARAM_SCALER_SIZE_WIDTH(x)		FIELD_PREP(GENMASK(15, 0), (x))
#define W6_CMD_ENC_SET_PARAM_SCALER			(W6_REG_BASE + 0x4B8)
#define		SET_PARAM_SCALER_COEF_MODE(x)		FIELD_PREP(GENMASK(2, 1), (x))
#define		SET_PARAM_SCALER_ENABLE(x)		FIELD_PREP(GENMASK(0, 0), (x))
#define W6_CMD_ENC_SET_PARAM_COLOR			(W6_REG_BASE + 0x4F8)
#define		SET_PARAM_COLOR_RANGE(x)		FIELD_PREP(GENMASK(25, 25), (x))
#define		SET_PARAM_COLOR_MATRIX_COEFF(x)		FIELD_PREP(GENMASK(24, 17), (x))
#define		SET_PARAM_COLOR_TRANS_CHAR(x)		FIELD_PREP(GENMASK(16, 9), (x))
#define		SET_PARAM_COLOR_PRIMARIES(x)		FIELD_PREP(GENMASK(8, 1), (x))
#define		SET_PARAM_COLOR_DESCRIPTION_PRESENT_ON	BIT(0)
#define W6_CMD_ENC_SET_PARAM_SAR			(W6_REG_BASE + 0x4FC)
#define		SET_PARAM_SAR_ASPECT_RATIO_IDC(x)	FIELD_PREP(GENMASK(8, 1), (x))
#define		SET_PARAM_SAR_ASPECT_RATIO_ENABLE(x)	FIELD_PREP(GENMASK(0, 0), (x))
#define W6_CMD_ENC_SET_PARAM_SAR_EXTENDED		(W6_REG_BASE + 0x500)
#define		SET_PARAM_SAR_EXTENDED_HEIGHT(x)	FIELD_PREP(GENMASK(31, 16), (x))
#define		SET_PARAM_SAR_EXTENDED_WIDTH(x)		FIELD_PREP(GENMASK(15, 0), (x))

/* ENCODER - ENC_PIC */
#define W6_CMD_ENC_PIC_BS_START				(W6_REG_BASE + 0x300)
#define W6_CMD_ENC_PIC_BS_SIZE				(W6_REG_BASE + 0x304)
#define W6_CMD_ENC_PIC_BS_OPTION			(W6_REG_BASE + 0x308)
#define W6_CMD_ENC_PIC_SEC_AXI				(W6_REG_BASE + 0x30C)
#define		ENC_PIC_SEC_AXI_RDO_ENABLE(x)		FIELD_PREP(GENMASK(1, 1), (x))
#define		ENC_PIC_SEC_AXI_LF_ENABLE(x)		FIELD_PREP(GENMASK(0, 0), (x))
#define W6_CMD_ENC_PIC_REPORT				(W6_REG_BASE + 0x310)
#define		ENC_PIC_REPORT_MV_HISTO_ENABLE(x)	FIELD_PREP(GENMASK(1, 1), (x))
#define W6_CMD_ENC_PIC_MV_HISTO0			(W6_REG_BASE + 0x318)
#define		ENC_PIC_MV_HISTO0_THRESHOLD0(x)		FIELD_PREP(GENMASK(31, 16), (x))
#define		ENC_PIC_MV_HISTO0_THRESHOLD1(x)		FIELD_PREP(GENMASK(15, 0), (x))
#define W6_CMD_ENC_PIC_MV_HISTO1			(W6_REG_BASE + 0x31C)
#define		ENC_PIC_MV_HISTO1_THRESHOLD2(x)		FIELD_PREP(GENMASK(31, 16), (x))
#define		ENC_PIC_MV_HISTO1_THRESHOLD3(x)		FIELD_PREP(GENMASK(15, 0), (x))
#define W6_CMD_ENC_PIC_CUSTOM_MAP_PARAM			(W6_REG_BASE + 0x320)
#define W6_CMD_ENC_PIC_CUSTOM_MAP_ADDR			(W6_REG_BASE + 0x324)
#define W6_CMD_ENC_PIC_SRC_PIC_IDX			(W6_REG_BASE + 0x32C)
#define		ENC_PIC_SRC_PIC_IDX_END			0xFFFFFFFF
#define W6_CMD_ENC_PIC_SRC_ADDR_Y			(W6_REG_BASE + 0x330)
#define W6_CMD_ENC_PIC_SRC_ADDR_U			(W6_REG_BASE + 0x334)
#define W6_CMD_ENC_PIC_SRC_ADDR_V			(W6_REG_BASE + 0x338)
#define W6_CMD_ENC_PIC_SRC_STRIDE			(W6_REG_BASE + 0x33C)
#define		ENC_PIC_SRC_STRIDE_L(x)			FIELD_PREP(GENMASK(31, 16), (x))
#define		ENC_PIC_SRC_STRIDE_C(x)			FIELD_PREP(GENMASK(15, 0), (x))
#define W6_CMD_ENC_PIC_SRC_FMT				(W6_REG_BASE + 0x340)
#define		ENC_PIC_SRC_FMT_C_FMT_IDC(x)		FIELD_PREP(GENMASK(30, 28), (x))
#define		ENC_PIC_SRC_FMT_CSC_24BIT(x)		FIELD_PREP(GENMASK(25, 25), (x))
#define		ENC_PIC_SRC_FMT_CSC_AYUV(x)		FIELD_PREP(GENMASK(24, 24), (x))
#define		ENC_PIC_SRC_FMT_CSC_ENABLE(x)		FIELD_PREP(GENMASK(20, 20), (x))
#define		ENC_PIC_SRC_FMT_CSC_FMT_ORDER(x)	FIELD_PREP(GENMASK(19, 16), (x))
#define		ENC_PIC_SRC_FMT_ENDIAN(x)		FIELD_PREP(GENMASK(15, 12), (x))
#define		ENC_PIC_SRC_FMT_10BIT_ORDER(x)		FIELD_PREP(GENMASK(6, 6), (x))
#define		ENC_PIC_SRC_FMT_10BIT_3PIXEL_4BYTE(x)	FIELD_PREP(GENMASK(5, 5), (x))
#define		ENC_PIC_SRC_FMT_10BIT_ENABLE(x)		FIELD_PREP(GENMASK(4, 4), (x))
#define		ENC_PIC_SRC_FMT_YUV422_PACKED_ORDER(x)	FIELD_PREP(GENMASK(3, 3), (x))
#define		ENC_PIC_SRC_FMT_CBCR_ORDER(x)		FIELD_PREP(GENMASK(2, 2), (x))
#define		ENC_PIC_SRC_FMT_2PLANE(x)		FIELD_PREP(GENMASK(1, 1), (x))
#define		ENC_PIC_SRC_FMT_YUV422_PACKED(x)	FIELD_PREP(GENMASK(0, 0), (x))
#define W6_CMD_ENC_PIC_SRC_AXI_SEL			(W6_REG_BASE + 0x348)
#define		ENC_PIC_SRC_AXI_SEL_PRIMARY_PORT	1
#define		ENC_PIC_SRC_AXI_SEL_PRP_PORT		0
#define W6_CMD_ENC_PIC_CODE_OPTION			(W6_REG_BASE + 0x34C)
#define		ENC_PIC_CODE_OPTION_ENCODE_VCL		BIT(1)
#define		ENC_PIC_CODE_OPTION_ENCODE_HEADER	BIT(0)
#define W6_CMD_ENC_PIC_PARAM				(W6_REG_BASE + 0x350)
#define		ENC_PIC_PARAM_INTRA_4X4(x)		FIELD_PREP(GENMASK(29, 28), (x))
#define		ENC_PIC_PARAM_FORCE_PIC_TYPE(x)		FIELD_PREP(GENMASK(23, 21), (x))
#define		ENC_PIC_PARAM_FORCE_PIC_TYPE_ENABLE(x)	FIELD_PREP(GENMASK(20, 20), (x))
#define		ENC_PIC_PARAM_FORCE_PIC_QP_B(x)		FIELD_PREP(GENMASK(19, 14), (x))
#define		ENC_PIC_PARAM_FORCE_PIC_QP_P(x)		FIELD_PREP(GENMASK(13, 8), (x))
#define		ENC_PIC_PARAM_FORCE_PIC_QP_I(x)		FIELD_PREP(GENMASK(7, 2), (x))
#define		ENC_PIC_PARAM_FORCE_PIC_QP_ENABLE(x)	FIELD_PREP(GENMASK(1, 1), (x))
#define		ENC_PIC_PARAM_PIC_SKIP_FLAG(x)		FIELD_PREP(GENMASK(0, 0), (x))
#define W6_CMD_ENC_PIC_LONGTERM_PIC			(W6_REG_BASE + 0x354)
#define W6_CMD_ENC_PIC_PREFIX_SEI_NAL_ADDR		(W6_REG_BASE + 0x358)
#define W6_CMD_ENC_PIC_PREFIX_SEI_INFO			(W6_REG_BASE + 0x35C)
#define W6_CMD_ENC_PIC_SUFFIX_SEI_NAL_ADDR		(W6_REG_BASE + 0x360)
#define W6_CMD_ENC_PIC_SUFFIX_SEI_INFO			(W6_REG_BASE + 0x364)
#define W6_CMD_ENC_PIC_CSC_COEFF0			(W6_REG_BASE + 0x374)
#define		ENC_PIC_CSC_COEFF0_RY(x)		FIELD_PREP(GENMASK(29, 20), (x))
#define		ENC_PIC_CSC_COEFF0_GY(x)		FIELD_PREP(GENMASK(19, 10), (x))
#define		ENC_PIC_CSC_COEFF0_BY(x)		FIELD_PREP(GENMASK(9, 0), (x))
#define W6_CMD_ENC_PIC_CSC_COEFF1			(W6_REG_BASE + 0x378)
#define		ENC_PIC_CSC_COEFF1_RCB(x)		FIELD_PREP(GENMASK(29, 20), (x))
#define		ENC_PIC_CSC_COEFF1_GCB(x)		FIELD_PREP(GENMASK(19, 10), (x))
#define		ENC_PIC_CSC_COEFF1_BCB(x)		FIELD_PREP(GENMASK(9, 0), (x))
#define W6_CMD_ENC_PIC_CSC_COEFF2			(W6_REG_BASE + 0x37C)
#define		ENC_PIC_CSC_COEFF2_RCR(x)		FIELD_PREP(GENMASK(29, 20), (x))
#define		ENC_PIC_CSC_COEFF2_GCR(x)		FIELD_PREP(GENMASK(19, 10), (x))
#define		ENC_PIC_CSC_COEFF2_BCR(x)		FIELD_PREP(GENMASK(9, 0), (x))
#define W6_CMD_ENC_PIC_CSC_COEFF3			(W6_REG_BASE + 0x380)
#define		ENC_PIC_CSC_COEFF3_OFFSET_Y(x)		FIELD_PREP(GENMASK(29, 20), (x))
#define		ENC_PIC_CSC_COEFF3_OFFSET_CB(x)		FIELD_PREP(GENMASK(19, 10), (x))
#define		ENC_PIC_CSC_COEFF3_OFFSET_CR(x)		FIELD_PREP(GENMASK(9, 0), (x))
#define W6_CMD_ENC_PIC_TIMESTAMP_LOW			(W6_REG_BASE + 0x448)
#define W6_CMD_ENC_PIC_TIMESTAMP_HIGH			(W6_REG_BASE + 0x44C)

/* ENCODER - QUERY : GET_RESULT */
#define W6_RET_ENC_RD_PTR				(W6_REG_BASE + 0x300)
#define W6_RET_ENC_WR_PTR				(W6_REG_BASE + 0x304)
#define W6_RET_ENC_NUM_REQUIRED_FBC_FB			(W6_REG_BASE + 0x308)
#define W6_RET_ENC_MIN_SRC_BUF_NUM			(W6_REG_BASE + 0x30C)
#define W6_RET_ENC_PIC_TYPE				(W6_REG_BASE + 0x310)
#define W6_RET_ENC_PIC_POC				(W6_REG_BASE + 0x314)
#define W6_RET_ENC_PIC_IDX				(W6_REG_BASE + 0x318)
#define W6_RET_ENC_PIC_SLICE_NUM			(W6_REG_BASE + 0x31C)
#define W6_RET_ENC_PIC_SKIP				(W6_REG_BASE + 0x320)
#define W6_RET_ENC_PIC_NUM_INTRA			(W6_REG_BASE + 0x324)
#define W6_RET_ENC_PIC_NUM_MERGE			(W6_REG_BASE + 0x328)
#define W6_RET_ENC_PIC_NON_REF_PIC_FLAG			(W6_REG_BASE + 0x32C)
#define W6_RET_ENC_PIC_NUM_SKIP				(W6_REG_BASE + 0x330)
#define W6_RET_ENC_PIC_AVG_CTU_QP			(W6_REG_BASE + 0x334)
#define W6_RET_ENC_PIC_BYTE				(W6_REG_BASE + 0x338)
#define W6_RET_ENC_GOP_PIC_IDX				(W6_REG_BASE + 0x33C)
#define W6_RET_ENC_USED_SRC_IDX				(W6_REG_BASE + 0x340)
#define W6_RET_ENC_PIC_NUM				(W6_REG_BASE + 0x344)
#define W6_RET_ENC_VCL_NUT				(W6_REG_BASE + 0x348)
#define W6_RET_ENC_PIC_DIST_LOW				(W6_REG_BASE + 0x350)
#define W6_RET_ENC_PIC_DIST_HIGH			(W6_REG_BASE + 0x354)
#define W6_RET_ENC_PIC_MAX_LATENCY_PICTURES		(W6_REG_BASE + 0x358)
#define W6_RET_ENC_HISTO_CNT0				(W6_REG_BASE + 0x360)
#define W6_RET_ENC_HISTO_CNT1				(W6_REG_BASE + 0x364)
#define W6_RET_ENC_HISTO_CNT2				(W6_REG_BASE + 0x368)
#define W6_RET_ENC_HISTO_CNT3				(W6_REG_BASE + 0x36C)
#define W6_RET_ENC_HISTO_CNT4				(W6_REG_BASE + 0x370)
#define W6_RET_ENC_WARN_INFO				(W6_REG_BASE + 0x3AC)
#define W6_RET_ENC_ERR_INFO				(W6_REG_BASE + 0x3B0)
#define W6_RET_ENC_ENCODING_SUCCESS			(W6_REG_BASE + 0x3B4)
#define W6_RET_ENC_SUM_ME0_X_DIR_LOWER			(W6_REG_BASE + 0x3B8)
#define W6_RET_ENC_SUM_ME0_X_DIR_HIGHER			(W6_REG_BASE + 0x3BC)
#define W6_RET_ENC_SUM_ME0_Y_DIR_LOWER			(W6_REG_BASE + 0x3C0)
#define W6_RET_ENC_SUM_ME0_Y_DIR_HIGHER			(W6_REG_BASE + 0x3C4)
#define W6_RET_ENC_SUM_ME1_X_DIR_LOWER			(W6_REG_BASE + 0x3C8)
#define W6_RET_ENC_SUM_ME1_X_DIR_HIGHER			(W6_REG_BASE + 0x3CC)
#define W6_RET_ENC_SUM_ME1_Y_DIR_LOWER			(W6_REG_BASE + 0x3D0)
#define W6_RET_ENC_SUM_ME1_Y_DIR_HIGHER			(W6_REG_BASE + 0x3D4)
#define W6_RET_ENC_SRC_Y_ADDR				(W6_REG_BASE + 0x3E8)
#define W6_RET_ENC_CUSTOM_MAP_ADDR			(W6_REG_BASE + 0x3EC)
#define W6_RET_ENC_PREFIX_SEI_NAL_ADDR			(W6_REG_BASE + 0x3F0)
#define W6_RET_ENC_SUFFIX_SEI_NAL_ADDR			(W6_REG_BASE + 0x3F4)
#define W6_RET_ENC_NUM_REQUIRED_COL_BUF			(W6_REG_BASE + 0x404)
#define W6_RET_ENC_TIMESTAMP_LOW			(W6_REG_BASE + 0x44C)
#define W6_RET_ENC_TIMESTAMP_HIGH			(W6_REG_BASE + 0x450)

#endif /* __WAVE6_REGDEFINE_H__ */
